//----------------------
// <auto-generated>
//    Generated using JSLibExport.cs in UnityAngularBridge project.
// </auto-generated>
//----------------------

/* eslint-disable */

import { Injectable, signal, WritableSignal, Signal } from "@angular/core";

// Module-scope writable signals (accessed by window callbacks below).
const sendSelectedObjectSignal: WritableSignal<string | null> = signal<string | null>(null, { equal: () => false });
const sendSceneReadySignal: WritableSignal<number> = signal<number>(0);
const sendObjectsListSignal: WritableSignal<string[]> = signal<string[]>([], { equal: () => false });

// Module-scope callback holders.
let requestDataFromWebHandler: ((query: string, respond: (result: string) => void) => void) | null = null;
let registerOnNavigationChangedCallback: ((data: string) => void) | null = null;

// Register window callbacks invoked by Unity's jslib.
/* eslint-disable @typescript-eslint/no-explicit-any */
(window as any)["sendSelectedObjectFromUnity"] = (objectId: string): void => {
  sendSelectedObjectSignal.set(objectId);
};
(window as any)["sendSceneReadyFromUnity"] = (): void => {
  sendSceneReadySignal.update(v => v + 1);
};
(window as any)["sendObjectsListFromUnity"] = (objectIds: string): void => {
  sendObjectsListSignal.set(objectIds.split("|"));
};
(window as any)["requestDataFromWebFromUnity"] = (query: string, respond: (result: string) => void): void => {
  requestDataFromWebHandler?.(query, respond);
};
(window as any)["registerOnNavigationChangedFromUnity"] = (handler: (data: string) => void): void => {
  registerOnNavigationChangedCallback = handler;
};

/**
 * Auto-generated service for Unity \u2192 Angular communication.
 * Signals are updated when Unity calls the corresponding jslib functions.
 * Register callback handlers to respond to Unity requests.
 * See: https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html
 */
@Injectable({
  providedIn: "root",
})
export class UnityJSLibExportedService {
  readonly sendSelectedObject: Signal<string | null> = sendSelectedObjectSignal.asReadonly();
  readonly sendSceneReady: Signal<number> = sendSceneReadySignal.asReadonly();
  readonly sendObjectsList: Signal<string[]> = sendObjectsListSignal.asReadonly();
  
  /** Register a handler for RequestDataFromWeb requests from Unity. */
  registerRequestDataFromWebHandler(handler: (query: string, respond: (result: string) => void) => void): void {
    requestDataFromWebHandler = handler;
  }
  
  /** Invoke the callback registered by Unity via RegisterOnNavigationChanged. */
  notifyOnNavigationChanged(data: string): void {
    registerOnNavigationChangedCallback?.(data);
  }
}
