//----------------------
// <auto-generated>
//    Generated using JSLibExport.cs by Jim Halewijn in UnityAngularBridge project.
// </auto-generated>
//----------------------

/* eslint-disable */

import { Injectable } from "@angular/core";
import { BehaviorSubject, Observable, Subject } from "rxjs";

// NOTE: These subjects are used as a more global scope, so we can access it in JavaScript function of Unity.
const sendSelectedObjectSubject: BehaviorSubject<string[]> = new BehaviorSubject<string[]>([]);
const sendSceneReadySubject: Subject<void> = new Subject<void>();
const sendObjectsListSubject: BehaviorSubject<string[]> = new BehaviorSubject<string[]>([]);

/**
 * NOTE: these functions are from unity webinteractions lib, meaning it is JavaScript.
 * See: https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html
 * In Unity the function is set to the window object, which is why we set it here with:
 * window["myfunctionName"] = this.myfunctionName;
 *
 * 'this' does not work as it is JavaScript.
 * As a workaround, myfunctionNameSubject is set outside this class scope to access it and subscribe to these listeners.
 *
 * These names are from the jslib file in UnityAngularBridge repo '/Assets/Plugins/BrowserInteractions.jslib' file.
 */
@Injectable({
  providedIn: "root",
})
export class UnityJSLibExportedService {
  public sendSelectedObject$: Observable<string[]> = sendSelectedObjectSubject.asObservable();
  public sendSceneReady$: Observable<void> = sendSceneReadySubject.asObservable();
  public sendObjectsList$: Observable<string[]> = sendObjectsListSubject.asObservable();
  
  constructor() {
    this.setupUnityListeners();
  }
  
  private setupUnityListeners(): void {
    window["sendSelectedObjectFromUnity"] = this.sendSelectedObjectFromUnity;
    window["sendSceneReadyFromUnity"] = this.sendSceneReadyFromUnity;
    window["sendObjectsListFromUnity"] = this.sendObjectsListFromUnity;
  }
  
  private sendSelectedObjectFromUnity(objectId: string): void {
    const split = objectId.split("|");
    sendSelectedObjectSubject.next(split);
  }
  
  private sendSceneReadyFromUnity(): void {
    sendSceneReadySubject.next();
  }
  
  private sendObjectsListFromUnity(objectIds: string): void {
    const split = objectIds.split("|");
    sendObjectsListSubject.next(split);
  }
}
