import { computed, inject, Injectable, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { UnityClient, IUnityInstance } from '../generated/unity-client';
import { UnityJSLibExportedService } from '../generated/unity-jslib-exported.service';

/**
 * Wraps the generated Unity bridge files with Angular Signals and Computed values.
 *
 * - `UnityClient` (generated by AngularExposedExport.cs) provides methods to call Unity.
 * - `UnityJSLibExportedService` (generated by JSLibExport.cs) provides observables for Unity events.
 *
 * This service converts RxJS observables to signals for use with OnPush change detection.
 */
@Injectable({ providedIn: 'root' })
export class UnityBridgeService {
  private readonly unityClient = inject(UnityClient);
  private readonly jsLibService = inject(UnityJSLibExportedService);

  // ----- Unity instance reference -----
  private readonly _unityInstance = signal<IUnityInstance | null>(null);
  readonly unityInstance = this._unityInstance.asReadonly();

  // ----- Signals from Unity events (Unity → Angular via JSLib) -----
  readonly selectedObject = toSignal(this.jsLibService.sendSelectedObject$, { initialValue: null });
  readonly objectsList = toSignal(this.jsLibService.sendObjectsList$, { initialValue: [] as string[] });

  // ----- Computed signals -----
  readonly objectCount = computed(() => this.objectsList().length);
  readonly hasSelection = computed(() => !!this.selectedObject());
  readonly isConnected = computed(() => !!this.unityInstance());

  /** Set the Unity WebGL instance (called after Unity finishes loading). */
  setUnityInstance(instance: IUnityInstance): void {
    this._unityInstance.set(instance);
  }

  // ----- Angular → Unity methods (via AngularExposed / UnityClient) -----

  loadObject(objectId: string): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_LoadObject(instance, objectId);
    }
  }

  setColor(colorHex: string): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_SetColor(instance, colorHex);
    }
  }

  toggleVisibility(): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_ToggleVisibility(instance);
    }
  }

  resetScene(): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_ResetScene(instance);
    }
  }
}
