#nullable enable
#if UNITY_EDITOR
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Xml.Linq;
using UnityEditor;
using UnityEngine;

namespace UnityAngularBridge
{
    /// <summary>
    /// Generates UnityClient.ts — a TypeScript class for calling Unity methods from Angular.
    /// Scans for [AngularExposed] methods and generates typed SendMessage wrappers.
    /// Supports XML doc → TSDoc and configurable output paths.
    /// </summary>
    [InitializeOnLoad]
    public class AngularExposedExport
    {
        private static readonly string _angularTsClientFileName = "UnityClient.ts";
        private static readonly string _tabString = "  ";
        private static readonly Dictionary<string, string> _xmlDocs = new();

        static AngularExposedExport()
        {
            LoadXmlDocumentation();
            GenerateUnityClient();
        }

        #region XmlDocumentation

        private static void LoadXmlDocumentation()
        {
            _xmlDocs.Clear();
            try
            {
                string xmlPath = Path.Combine(Application.dataPath, "..", "Library", "ScriptAssemblies", "Assembly-CSharp.xml");
                if (!File.Exists(xmlPath)) return;

                XDocument doc = XDocument.Load(xmlPath);
                foreach (var member in doc.Descendants("member"))
                {
                    string? name = member.Attribute("name")?.Value;
                    string? summary = member.Element("summary")?.Value;
                    if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(summary))
                    {
                        string cleaned = summary.Trim().Replace("\r\n", " ").Replace("\n", " ");
                        while (cleaned.Contains("  "))
                            cleaned = cleaned.Replace("  ", " ");
                        _xmlDocs[name] = cleaned;
                    }
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[UnityAngularBridge] Could not load XML documentation: {e.Message}");
            }
        }

        private static string GetXmlDocumentation(Type type, MethodInfo methodInfo)
        {
            string paramTypes = string.Join(",",
                methodInfo.GetParameters().Select(p => p.ParameterType.FullName ?? p.ParameterType.Name));
            string memberName = methodInfo.GetParameters().Length > 0
                ? $"M:{type.FullName}.{methodInfo.Name}({paramTypes})"
                : $"M:{type.FullName}.{methodInfo.Name}";

            return _xmlDocs.TryGetValue(memberName, out string? doc) ? doc : string.Empty;
        }

        #endregion

        #region GenerateUnityClient

        private static void GenerateUnityClient()
        {
            string outputPath = UnityAngularBridgeSettings.GetUnityClientOutputPath();
            using IndentedTextWriter writer = new(
                new StreamWriter(Path.Combine(outputPath, _angularTsClientFileName)) { AutoFlush = true },
                _tabString);

            AddAutoGeneratedFileCommentLines(writer);
            AddInjectibleClassWithImportLines(writer);
            GetAndAddMethodsLines(writer);
            AddClassClosingLines(writer);
            AddIUnityInstanceInterfaceLines(writer);
        }

        private static void AddAutoGeneratedFileCommentLines(IndentedTextWriter writer)
        {
            writer.WriteLine("//----------------------");
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine("//    Generated using AngularExposedExport.cs in UnityAngularBridge project.");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine("//----------------------");
            writer.WriteLine(string.Empty);
            writer.WriteLine("/* eslint-disable */");
            writer.WriteLine(string.Empty);
        }

        private static void AddInjectibleClassWithImportLines(IndentedTextWriter writer)
        {
            writer.WriteLine("import { Injectable } from \"@angular/core\";");
            writer.WriteLine(string.Empty);
            writer.WriteLine("@Injectable()");
            writer.WriteLine("export class UnityClient {");
            writer.Indent++;
        }

        private static void GetAndAddMethodsLines(IndentedTextWriter writer)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            IEnumerable<Type> publicClasses = assembly.GetExportedTypes().Where(p => p.IsClass);

            foreach (Type type in publicClasses)
            {
                IEnumerable<MethodInfo> methodInfos = type
                    .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Static)
                    .Where(m => m.GetCustomAttributes(typeof(AngularExposedAttribute), false).Length > 0);

                foreach (MethodInfo methodInfo in methodInfos)
                {
                    object[] methodAttributes = methodInfo.GetCustomAttributes(typeof(AngularExposedAttribute), false);
                    string gameObjectName = string.Empty;
                    string attrDoc = string.Empty;

                    foreach (AngularExposedAttribute attribute in methodAttributes.Cast<AngularExposedAttribute>())
                    {
                        gameObjectName = attribute.GameObjectName;
                        attrDoc = attribute.Documentation;
                    }

                    string methodName = methodInfo.Name;

                    // Get documentation: attribute override > XML docs
                    string documentation = !string.IsNullOrEmpty(attrDoc)
                        ? attrDoc
                        : GetXmlDocumentation(type, methodInfo);

                    string parameterType = string.Empty;
                    string parameterName = string.Empty;
                    ParameterInfo[] parameters = methodInfo.GetParameters();
                    if (parameters.Length > 1)
                    {
                        throw new InvalidOperationException($"Method {methodName} is only allowed to have 1 argument");
                    }
                    else if (parameters.Length == 1)
                    {
                        parameterType = ParameterTypeToTypescriptType(parameters[0].ParameterType);
                        parameterName = parameters[0].Name ?? "data";
                    }

                    AddMethodLines(writer, gameObjectName, methodName, parameterType, parameterName, documentation);
                }
            }
        }

        private static void AddMethodLines(IndentedTextWriter writer, string gameObjectName, string methodName,
            string? parameterType, string? parameterName, string documentation)
        {
            bool hasParameter = !string.IsNullOrEmpty(parameterName);

            if (!string.IsNullOrEmpty(documentation))
            {
                writer.WriteLine($"/** {documentation} */");
            }

            if (hasParameter)
            {
                writer.WriteLine($"public {FirstCharToLowerCase(gameObjectName)}_{methodName}(unityInstance: IUnityInstance, {parameterName}: {parameterType}): void {{");
                writer.Indent++;
                writer.WriteLine($"unityInstance?.SendMessage(\"{gameObjectName}\", \"{methodName}\", {parameterName});");
                writer.Indent--;
                writer.WriteLine("}");
                writer.WriteLine(string.Empty);
            }
            else
            {
                writer.WriteLine($"public {FirstCharToLowerCase(gameObjectName)}_{methodName}(unityInstance: IUnityInstance): void {{");
                writer.Indent++;
                writer.WriteLine($"unityInstance?.SendMessage(\"{gameObjectName}\", \"{methodName}\");");
                writer.Indent--;
                writer.WriteLine("}");
                writer.WriteLine(string.Empty);
            }
        }

        private static void AddClassClosingLines(IndentedTextWriter writer)
        {
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine(string.Empty);
        }

        private static void AddIUnityInstanceInterfaceLines(IndentedTextWriter writer)
        {
            writer.WriteLine("export interface IUnityInstance {");
            writer.Indent++;
            writer.WriteLine("SendMessage(gameObjectName: string, methodName: string, data?: unknown): void;");
            writer.WriteLine("SetFullscreen(value: number): void;");
            writer.WriteLine("Quit(): Promise<unknown>;");
            writer.Indent--;
            writer.WriteLine("}");
        }

        #endregion

        #region TypeConversion

        private static string ParameterTypeToTypescriptType(object parameterType)
        {
            return parameterType.ToString() switch
            {
                "System.String" => "string",
                "System.Int32" => "number",
                "System.Single" => "number",
                _ => throw new InvalidOperationException(
                    $"ParameterType {parameterType} is not supported. Only string and number variants are allowed."),
            };
        }

        #endregion

        #region Utilities

        private static string? FirstCharToLowerCase(string? str)
        {
            if (!string.IsNullOrEmpty(str) && char.IsUpper(str[0]))
            {
                return str.Length == 1 ? char.ToLower(str[0]).ToString() : char.ToLower(str[0]) + str[1..];
            }
            return str;
        }

        #endregion
    }
}
#endif
